"""add tech debt tables

Revision ID: 305f474fb39f
Revises: f8a2b1c0d3e4
Create Date: 2026-03-23 21:18:37.294427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305f474fb39f'
down_revision = 'f8a2b1c0d3e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tech_debt_items",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("repository_id", sa.String(), sa.ForeignKey("repositories.id"), nullable=False),
        sa.Column("service_id", sa.String(), sa.ForeignKey("services.id"), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("code_snippet", sa.Text(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("impact_score", sa.Float(), nullable=True),
        sa.Column("effort_estimate", sa.String(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=True, server_default="open"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "tech_debt_reports",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("repository_id", sa.String(), sa.ForeignKey("repositories.id"), nullable=False),
        sa.Column("total_debt_score", sa.Float(), nullable=True),
        sa.Column("debt_density", sa.Float(), nullable=True),
        sa.Column("code_quality_score", sa.Float(), nullable=True),
        sa.Column("architecture_score", sa.Float(), nullable=True),
        sa.Column("dependency_score", sa.Float(), nullable=True),
        sa.Column("documentation_score", sa.Float(), nullable=True),
        sa.Column("test_coverage_score", sa.Float(), nullable=True),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("items_by_category", sa.JSON(), nullable=True),
        sa.Column("items_by_severity", sa.JSON(), nullable=True),
        sa.Column("report_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "debt_remediation_plans",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("repository_id", sa.String(), sa.ForeignKey("repositories.id"), nullable=False),
        sa.Column("plan_name", sa.String(), nullable=True),
        sa.Column("total_estimated_effort", sa.String(), nullable=True),
        sa.Column("priority_breakdown", sa.JSON(), nullable=True),
        sa.Column("sprint_allocation", sa.JSON(), nullable=True),
        sa.Column("roi_analysis", sa.JSON(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "debt_metrics_history",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("repository_id", sa.String(), sa.ForeignKey("repositories.id"), nullable=False),
        sa.Column("total_debt_score", sa.Float(), nullable=True),
        sa.Column("debt_density", sa.Float(), nullable=True),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("items_by_category", sa.JSON(), nullable=True),
        sa.Column("remediation_velocity", sa.Float(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("debt_metrics_history", if_exists=True)
    op.drop_table("debt_remediation_plans", if_exists=True)
    op.drop_table("tech_debt_reports", if_exists=True)
    op.drop_table("tech_debt_items", if_exists=True)
    # ### end Alembic commands ###
