"""add tech debt tables

Revision ID: 51535ee764d6
Revises: 305f474fb39f
Create Date: 2026-03-23 21:22:09.760518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51535ee764d6'
down_revision = '305f474fb39f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
